### ISSUE TITLE
github login occasionally hangs and returns internal server error

### ISSUE THREAD

**Issue by Marak** [JavascriptBattle/javascript-battle-website#297]
Hello.

I've noticed a few times in the past couples of days at occasional times ( like right now ) the login hangs for awhile and then returns a blank white page with "Internal Server Error" at something like http://www.javascriptbattle.com/auth/github/callback?code=9d5f8663d26cc943e542

Not sure what the cause is.

**Comment by gjtrowbridge** [comment]
This should now be FIXED.  Thanks for the patience everyone (I know it was a long time coming).  Please let me know if you see this or a related issue continue to crop up.

**Comment by Yahkob** [comment]
@gjtrowbridge was this a code or azure related fix?

**Comment by gjtrowbridge** [comment]
Code:https://github.com/JavascriptBattle/javascript-battle-website/commit/41461efb3aad5e37bfe8fe6c8740d2fc21f696de
