### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by m0ose** [JavascriptBattle/javascript-battle-website#339]
I got this error
GET http://oranlooney.com/static/javascript/deepCopy.js net::ERR_CONNECTION_REFUSED

It looks like the wrong url.

**Comment by Yahkob** [comment]
Hey @m0ose what steps can I follow to reproduce this?

**Comment by Yahkob** [comment]
I think it's possible you are referencing this link in javascript-battle-testing-website: https://github.com/JavascriptBattle/javascript-battle-testing-website/blob/4f7f3d84fef9dbfb95508f1f20aa65250cb50c30/public/index.html

**Comment by m0ose** [comment]
Yeah, I was talking about the testing site. Sorry for the confusion.

**Comment by Yahkob** [comment]
Its ok @m0ose lets open up a issue there, I'll try to find a replacement url for deepCopy I think @forrestbthomas wrote most of the testing site. If you open a PR with a new working url ill merge it in
