### ISSUE TITLE
Battle is missing the first row of the board

### ISSUE THREAD

**Issue by Asuza** [JavascriptBattle/javascript-battle-website#340]
When viewing the daily battle at http://www.javascriptbattle.com/, the top row of the board is missing. It makes it difficult to watch the battle unfold.

**Comment by natedsaint** [comment]
:+1: I've also noticed that the scaling doesn't work on widescreen, the tiles become too large (might be related issue) http://i.imgur.com/wcm9YLa.png

**Comment by Yahkob** [comment]
Hey @Asuza and @natedsaint the issue with the top row not rendering is an issue with Azure not deploying the correctly built grunt output I think all I need to do is rebuild locally and push to prod. I did this earlier and it fixed it for what seemed like a few days then it appears Azure or someone with access to our deployment may have reverted to the old build. As far the widescreen issue this is just incorrect @media queries. Hopefully will get around to fixing it in the next few days but feel free to open up a PR in the mean time

**Comment by Yahkob** [comment]
@Asuza , the top row is back after building grunt. Hopefully it doesn't revert to the old code again going to close unless it happens for you again. @natedsaint I

**Comment by Yahkob** [comment]
@Asuza weird, I merged my change into master and it was working for a little bit, going to try to get access to our Azure account and check why its reverting to the old stuff. Going to reopen

**Comment by Asuza** [comment]
@Yahkob, is it always reverting to a very specific commit? Or just some random commit? Anyway, good luck. I've no experience with Azure.

**Comment by Yahkob** [comment]
Yeah, its bizarre. It might be something with the Grunt build. Im going to check our Grunt.js and deployment out tonight and see whats going on.

**Comment by Asuza** [comment]
@Yahkob, if you are going to do a deploy, I have a PR to fix the Battle Testing site (assuming they can be deployed together).

**Comment by Yahkob** [comment]
@Asuza sure, let me check it out.

**Comment by Yahkob** [comment]
@Asuza I added very simple debug support ( literally one console.log() ) if you set url params to /?debug=true and so far its working. Let me know if the top row stops rendering again and if you don't get the log then we'll no for sure if its an issue with deployment or with some grunt weirdness

**Comment by Asuza** [comment]
As of right now, the top row is showing up. I'll check it again later and see what happens.

**Comment by Yahkob** [comment]
Looks good this morning. Will reopen if it somehow reverts again.
