### ISSUE TITLE
Unable to start the server

### ISSUE THREAD

**Issue by Asuza** [JavascriptBattle/javascript-battle-website#344]
I'm having some issues getting the battle website running locally. I cloned the repo and ran the following:

    npm install
    bower install

And everything seemed to go well after minor finagling. However, when I run:

    node server.js

I then get the following repeating error message.
```
*****
Error connecting to database: Sat Oct 03 2015 03:21:30 GMT-0500 (CDT)
[Error: failed to connect to [localhost:27017]]
*****
Will attempt to reconnect in 400 milliseconds (49 attempt(s) remaining)... Sat Oct 03 2015 03:21:30 GMT-0500 (CDT)
*****
Error connecting to database: Sat Oct 03 2015 03:21:30 GMT-0500 (CDT)
[Error: failed to connect to [localhost:27017]]
*****
Will attempt to reconnect in 400 milliseconds (48 attempt(s) remaining)... Sat Oct 03 2015 03:21:30 GMT-0500 (CDT)
*****
```

I believe it's related to MongoDB. Is that something I need to set up separately from the app? I don't know if the application is supposed to start a MongoDB instance or not. Please let me know how to proceed. Thanks!

**Comment by Yahkob** [comment]
This isn't a bug, you'll need to clone javascript battle webworkers then run nodemon/node local-run/run-fake-games-local.js make sure you have webworkers-root-dir/secrets.js configured to do this.
