### ISSUE TITLE
Site is stopped

### ISSUE THREAD

**Issue by Asuza** [JavascriptBattle/javascript-battle-website#345]
Just in case it shouldn't be happening, I wanted to let you know that the site says "Error 403 - This web app is stopped." right now, when visiting http://www.javascriptbattle.com/

**Comment by Yahkob** [comment]
Hmm can you check this out when you have a chance @gjtrowbridge ?

**Comment by Asuza** [comment]
I don't know what kind of monitoring you have in place, so I'm just going to update every once in a while. As of now, the site is still "stopped".

**Comment by Yahkob** [comment]
Hey,

So unfortunately we decided to shut JSBattle down. The person who is in
charge of deployment costs is Greg and at the moment it's costing him $800+
to keep the site up. We had a good run and we're very sad to go. I think at
some point we'll add some instructions on how to deploy JSBattle and get it
running on your own deployment.

Best,
Jake

*Jake Harclerode*

*Software Engineer*
*619-786-4355*
<http://linkedin.com/in/jakeharclerode>   <http://github.com/yahkob>
<http://jakeharclerode.com>

**Comment by natedsaint** [comment]
:100:

**Comment by gjtrowbridge** [comment]
Hey all, we're super bummed to announce this, but we've decided to stop JavascriptBattle.  We're all very busy with full-time jobs,/families/life, and the cost of deploying the site had reached the point where it no longer made sense.  We'll put up some sort of landing page with this announcement soon.

Thanks so much for playing our game and for all the support!  (and feel free to email us directly if you have questions/comments)

**Comment by Alfredo-Delgado** [comment]
![bummer](https://raw.githubusercontent.com/JavascriptBattle/javascript-battle-website/stable/public/img/grave.png)

**Comment by Yahkob** [comment]
:joy: :clap:

**Comment by Asuza** [comment]
@gjtrowbridge, just out of curiosity, how many people were playing the game? Do you have any other interesting stats to throw at us?
